<img src="http://pandas.pydata.org/_static/pandas_logo.png" style="width:400px;height:80px;">
# <font color='red'>Pandas Tutorial On Stock Price Analysis</font>

*This tutorial will cover how to retrieve stock price from google finance using pandas data reader. The analysis of stock is done by plotting its high, low, close, volumne values in table and a chart. Charts are of two types,*

1. Line Chart
2. Bar Chart

If you don't know what is stock then first **watch this video to gain understanding on fundamentals of stocks and investing**,

In [1]:
%%HTML
<iframe width="560" height="315" src="https://www.youtube.com/embed/XRO6lEu9-5w" frameborder="0" allowfullscreen></iframe>

In [4]:
import pandas_datareader as pdr
pdr.get_data_yahoo('AAPL')

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2010-01-04,30.490000,30.642857,30.340000,30.572857,27.613066,123432400
2010-01-05,30.657143,30.798571,30.464285,30.625713,27.660807,150476200
2010-01-06,30.625713,30.747143,30.107143,30.138571,27.220825,138040000
2010-01-07,30.250000,30.285715,29.864286,30.082857,27.170504,119282800
2010-01-08,30.042856,30.285715,29.865715,30.282858,27.351143,111902700
2010-01-11,30.400000,30.428572,29.778572,30.015715,27.109863,115557400
2010-01-12,29.884285,29.967142,29.488571,29.674286,26.801487,148614900
2010-01-13,29.695715,30.132856,29.157143,30.092857,27.179537,151473000
2010-01-14,30.015715,30.065714,29.860001,29.918571,27.022121,108223500
2010-01-15,30.132856,30.228571,29.410000,29.418571,26.570528,148516900
2010-01-19,29.761429,30.741428,29.605715,30.719999,27.745962,182501900
2010-01-20,30.701429,30.792856,29.928572,30.247143,27.318890,153038200
2010-01-21,30.297142,30.472857,29.601429,29.724285,26.846643,152038600
2010-01-22,29.540001,29.642857,28.165714,28.250000,25.515087,220441900
2010-01-25,28.930000,29.242857,28.598572,29.010000,26.201517,266424900
2010-01-26,29.421429,30.530001,28.940001,29.420000,26.571819,466777500
2010-01-27,29.549999,30.082857,28.504286,29.697144,26.822136,430642100
2010-01-28,29.275715,29.357143,28.385714,28.469999,25.713791,293375600
2010-01-29,28.725714,28.885714,27.178572,27.437143,24.780926,311488100
2010-02-01,27.481428,28.000000,27.328571,27.818571,25.125425,187469100
2010-02-02,27.987143,28.045713,27.625713,27.980000,25.271231,174585600
2010-02-03,27.881428,28.600000,27.774286,28.461428,25.706045,153832000
2010-02-04,28.104286,28.338572,27.367144,27.435715,24.779634,189413000
2010-02-05,27.518572,28.000000,27.264286,27.922857,25.219614,212576700
2010-02-08,27.955715,28.268572,27.714285,27.731428,25.046721,119567700
2010-02-09,28.059999,28.214285,27.821428,28.027143,25.313808,158221700
2010-02-10,27.984285,28.085714,27.751429,27.874287,25.175749,92590400
2010-02-11,27.840000,28.535715,27.722857,28.381428,25.633789,137586400
2010-02-12,28.301428,28.805714,27.928572,28.625713,25.854427,163867200
2010-02-16,28.848572,29.098572,28.788572,29.057142,26.244091,135934400
...,...,...,...,...,...,...
2017-06-20,146.869995,146.869995,144.940002,145.009995,145.009995,24900100
2017-06-21,145.520004,146.070007,144.610001,145.869995,145.869995,21265800
2017-06-22,145.770004,146.699997,145.119995,145.630005,145.630005,19106300
2017-06-23,145.130005,147.160004,145.110001,146.279999,146.279999,35439400
2017-06-26,147.169998,148.279999,145.380005,145.820007,145.820007,25692400
2017-06-27,145.009995,146.160004,143.619995,143.729996,143.729996,24761900
2017-06-28,144.490005,146.110001,143.160004,145.830002,145.830002,22082400
2017-06-29,144.710007,145.130005,142.279999,143.679993,143.679993,31499400
2017-06-30,144.449997,144.960007,143.779999,144.020004,144.020004,23024100
2017-07-03,144.880005,145.300003,143.100006,143.500000,143.500000,14258300
2017-07-05,143.690002,144.789993,142.720001,144.089996,144.089996,21569600
2017-07-06,143.020004,143.500000,142.410004,142.729996,142.729996,24128800
2017-07-07,142.899994,144.750000,142.899994,144.179993,144.179993,19201700
2017-07-10,144.110001,145.949997,143.369995,145.059998,145.059998,21090600
2017-07-11,144.729996,145.850006,144.380005,145.529999,145.529999,19781800
2017-07-12,145.869995,146.179993,144.820007,145.740005,145.740005,24884500
2017-07-13,145.500000,148.490005,145.440002,147.770004,147.770004,25199400
2017-07-14,147.970001,149.330002,147.330002,149.039993,149.039993,20132100
2017-07-17,148.820007,150.899994,148.570007,149.559998,149.559998,23793500
2017-07-18,149.199997,150.130005,148.669998,150.080002,150.080002,17868800
2017-07-19,150.479996,151.419998,149.949997,151.020004,151.020004,20923000
2017-07-20,151.500000,151.740005,150.190002,150.339996,150.339996,17243700
2017-07-21,149.990005,150.440002,148.880005,150.270004,150.270004,26252600
2017-07-24,150.580002,152.440002,149.899994,152.089996,152.089996,21493200
2017-07-25,151.800003,153.839996,151.800003,152.740005,152.740005,18853900
2017-07-26,153.350006,153.929993,153.059998,153.460007,153.460007,15781000
2017-07-27,153.750000,153.990005,147.300003,150.559998,150.559998,32476300
2017-07-28,149.889999,150.229996,149.190002,149.500000,149.500000,17213700
2017-07-31,149.899994,150.330002,148.130005,148.729996,148.729996,19614200
2017-08-01,149.100006,150.220001,148.410004,150.050003,150.050003,23716478

In [2]:
import pandas as pd  #Not essential here, just for try
import numpy as np   #Not essential here, just for try
#import pandas.io.data as web
import pandas_datareader as web  #https://github.com/pydata/pandas-datareader
#from pandas_datareader import data as web
df = web.DataReader('AAPL', 'google', '2016/1/1', '2017/1/1')
df.head()

ImportError: The pandas.io.data module is moved to a separate package (pandas-datareader). After installing the pandas-datareader package (https://github.com/pydata/pandas-datareader), you can change the import ``from pandas.io import data, wb`` to ``from pandas_datareader import data, wb``.

In [3]:
%matplotlib inline
df.plot(y="Close", color="Green")

NameError: name 'df' is not defined

In [1]:
df.plot.bar(y="Volume")

NameError: name 'df' is not defined

In [2]:
%system ls

['jupyter_architecture.png',
 'jupyter_stocks.ipynb',
 'myFirstNotebook_kpa.ipynb',
 'myPandasTutorialWalkthrough1.ipynb',
 'pandas_tutorial_on_stock_price.ipynb',
 'pandas_tutorial_on_stock_price.py',
 'python_pandas_notebook.ipynb',
 'readme.txt']

In [3]:
!pwd

/Users/kpadhikari/Desktop/BigFls/CLAS12/GitProj/KPAdhikari/PythonStuff/IPython_Jupyter_Notebooks